### ISSUE TITLE
Suggestion about the history bug

### ISSUE THREAD

**Issue by Mangome** [pachanka/Ptty#3]
Hi pachanka, 
I'v been trying this Ptty tool for a while and thank you for the great job.I have a little suggestion about the history bug, maybe you can reset the hcurrent to 0 when a command is submitted, then the history should work in a good order. 
Thanks again.

**Comment by pachanka** [comment]
Hi Mangome, I've tested and added your bug fix to the repos ("v0.0.3" and "latest"). Thanks a bunch for the fix, it must have slipped my mind at some point to reset the history counter.
