### ISSUE TITLE
better regex for cmd parsing

### ISSUE THREAD

**Issue by wehowski** [pachanka/Ptty#5]
Hello,
var tokens = value.split( /\s+/ );

I would like to parse quoted arguments.
Like this:

 var tokens = value.split( /(?:  " ((?:(?<=\\\\)"|[^"])*) "|  ' ((?:(?<=\\\\)'|[^'])*) '|  (\S+))/x );

so I can get 

$ command --option="A string value" -usw

But it does not work as expected..., maybe there is a workaround available?

thanks!
p.s.: I'm quite new to regular expressions in javascript

**Comment by pachanka** [comment]
Hi,

As far as I know, its better to use an expression to tokenize your string and later parse it by iterating over the matched tokens.

I've been using something like this:

    // A hard command ...
    var cmd = 'first second "argument.sh -xyz" --foo="bar \'baz\' 123" -abc -d \'greedy lazy regex\' third';
    // Regex to return tokens and $.grep and $.trim to clean the array ...
    var args = $.grep( cmd.match(/((-{1,2})?\S+\s?)?(["']((?:\\.|[^"\\])*)["'])?|\S+/g), function (n) { return $.trim(n) });
    // Array [ "first ", "second "argument.sh -xyz"", "--foo="bar 'baz' 123"", "-abc ", "-d 'greedy lazy regex'", "third" ]

Now all you have to do is put it in a command or a callback and you're golden.

**Comment by wehowski** [comment]
Yes, thank you very much!! It's working now.


      
        
      var stripQuotes = function(a) {
            if ((a.charAt(0) === '"' && a.charAt(a.length-1) === '"')
             || a.charAt(0) ===  "'" && a.charAt(a.length-1) === "'") {
                 return a.substr(1, a.length-2);
            }
           return a.trim();
       };

       $.register_command(
            'frdl',
            'Send frdl command to an selected endpoint.',
            'frdl [ mixed ]',
            function(tokens) {
            	var i = 0, j, u, url = THIS.URL_JSONP, expect = 'jsonp', method = 'GET';
                var out = '', debug = false, quiet = false, typeOut = 'print', preparse = false;
                var k,toks,cmd = tokens.join(' ').trim(), kvp, _data = {}, _jsonpCallback = "frdlBounce";
                var tokens = [];
                var toks = $.grep( cmd.match(/((-{1,2})?\S+\s?)?(["']((?:\\.|[^"\\])*)["'])?|\S+/g), function (n) { return $.trim(n) });
                for(i in toks){
       	             tokens.push(toks[i]);
				}
	
					    
	            for(i = 0; i < tokens.length; i++){
  					 if(   '-' === tokens[i].substr(0 , 1) 
  					    && '--' !== tokens[i].substr(0 , 2) 
  					    && tokens[i].length > 2 ){
  						 for(j = 1; j < tokens[i].length; j++){
						 	tokens.push('-' + tokens[i][j]);
						 }  
						 tokens[i] = '';
					 }                	
                }				
        
				
							
	            for(i = 0; i < tokens.length; i++){		
                    tokens[i] = stripQuotes(tokens[i]);	
	                              	
                    if('preparse' === tokens[i] || '-p' === tokens[i]){
				    	preparse = true;
				    }              	
                    if('bounce' === tokens[i] || '-b' === tokens[i]){
				    	url = THIS.URL_CLIENT;
				    }
	                if('debug' === tokens[i] || '-d' === tokens[i]){
				    	debug = true;
				    	
				    }			    
	                if('quiet' === tokens[i] || '-q' === tokens[i]){
				    	quiet = true;
				    }	
				    	
                  if(true === new RegExp("\=").test(tokens[i])){
						 kvp = explode('=', tokens[i], 2);
                         kvp[1] = stripQuotes(kvp[1]);
 
                   
						 if('--' === kvp[0].substr(0 , 2) ){
						 	kvp[0]=kvp[0].substr(2 , kvp[0].length);
						 }
						 
						 
						  _data[kvp[0]] = kvp[1];
						  
						  
						  
						 if(  'POST' === kvp[0] 
						   || 'GET' === kvp[0]
						   || 'PUT' === kvp[0] 
						   || 'DELETE' === kvp[0]
						   || 'HEAD' === kvp[0]){
						 	 method = kvp[0];
						 	 url =  kvp[1];
						 }
						 
						
						 if('callback' === kvp[0]){
						 	 _jsonpCallback = kvp[1];
						 }
						
						if('expect' === kvp[0]){
						 	 expect = kvp[1];
						 }					 
						
						if('method' === kvp[0]){
						 	 method = kvp[1];
						 }							 
					}else{
						 if('-' === tokens[i].substr(0 , 1) ){
						 	tokens[i]=tokens[i].substr(1 , tokens[i].length);
						 }
						 _data[tokens[i]] = true;
					}
				}

**Comment by pachanka** [comment]
Well done.

The regex itself is still buggy when used with inner quotes double or single, so it might be a good idea to search and convert the quoted text in to HTML entities or some UTF-8 equivalent.

As they say, done is better than perfect.

**Comment by wehowski** [comment]
Hello again, 
I would like to share my argumentsParser how it is yet:

````
/* from php: http://www.phpclasses.org/package/9018-PHP-Parse-and-extract-a-command-line-arguments-string.html */ 
var parseArgs = function( cmd )
 {
  var $args = (true === cmd instanceof Array) ? cmd : $.grep( cmd.match(/((-{1,2})?\S+s?)?(["']((?:\\.|[^"'\\])*)["'])?|\S+/g), function (n) { return $.trim(n) });
 	
 	
  var $esc = false;

  var $ret = {
    'command' : [],
    'commands' : [],
    'options' : [],
    'flags'    : [],
    'args' : [],
    'tokens' : []
   };
 
  var $k = -1;

  while( $arg = $args.shift() )
  {
   $k++;

    if ( $arg.substr( 0, 2 ) === '--' )
    {

     var $value = "";
     var $com   = $arg.substr( 2 );

      if(strpos($com,'='))
       {
          var _list = explode("=",$com,2);
          $com = _list[0];
          $value = _list[1];
       }

    var $quotes = ''; 
	 
     if( ($value.substr(0, 1) === '"' || $value.substr( 0, 1) === "'") && $value.substr( $value.length-1, 1) !== "'"  && $value.substr($value.length-1, 1) !== '"' )
      {
        $quotes = $value.substr( 0, 1);
        while($args.length > 0)
         {
           var $v = $args.shift();
		   if(strpos($v,'\\') !== false){$esc = true;}
           $value += $v+ ' ';  
           
           if($esc === false && ((strpos($v,'"') !== false && $quotes === '"') || (strpos($v,"'") !== false && $quotes === "'")))break;
		   if($esc === true && ((strpos($v,'"') !== false && $quotes === '"') || (strpos($v,"'") !== false && $quotes === "'"))){$esc = false;}
         }
		 
		 /*
        $value = trim($value, self::SPACE);
        $value = trim($value, '"');
        $value = trim($value, "'");
        */
        $value = $value.replace(/^\s+|\s+$/g,'');
        $value = $value.replace(/^"|"$/g,'');
        $value = $value.replace(/^'|'$/g,'');
     }


     /* $value = trim($value , '"\''); */
      $value = $value.replace(/^["']|["']$/g,'');
	  if(''===$value.trim())$value = null;

      $ret.options.push( {
	        'opt' : $com,
	        'value' : $value.trim(),
	        'pos' : $k,
	        'quotes':$quotes
	    });
      $ret.tokens.push('--'+ $value.trim() );	    
	    
      continue;

    }

    if ( $arg.substr(0, 1 ) === '-' && $arg.substr( 0, 2 ) !== '--')
    {
      for (var $i = 1; 'undefined' !== typeof $arg[$i] ; $i++){
	  	$ret.flags.push({
			   'flag' :  $arg[$i].trim(),
               'pos' : $k,
	  
	     });
	      $ret.tokens.push( '-'+$arg[$i] );	
	  }
     /*   $ret.flags[$arg[$i]] = {
			   'flag' :  $arg[$i],
               'pos' : $k,
	  
	     };
	     */
      continue;
    }

    $ret.commands.push({'cmd' : $arg.trim(), 'pos' : $k});
    $ret.tokens.push( $arg.trim() );	
    continue;
  }

 $ret.args = $ret.commands;
/*  $ret.command = $ret.args.shift(); */
 $ret.command = $ret.args[0];
 /* unset($ret['commands']); */
 return $ret;
 };

````

**Comment by pachanka** [comment]
Hello @wehowski thanks for the feedback.

I'm afraid this thread has fallen behind. Ptty is at v.0.0.5 and includes its own tested [tokenize](http://goto.pachanka.org/ptty/docs/#tokenize) method, you can now define what your expected options are when you register the command as described [here](http://goto.pachanka.org/ptty/docs/#passing-arguments).

**Comment by wehowski** [comment]
Thank you @pachanka  !
I do not want to reopen the thread, just added this for completeness.

> Ptty is at v.0.0.5
I will look into it.

>  you can now define what your expected options are
Well, I just needed a tokenizer, without any cli(expected options) or gui, so I can pass a command to any cli (and then gui). My cli loads commands(expected options, and repl, interpreter, execution ) depending on the parsed arguments dynamically, rather than pre-defining expected tokens, 
also seperating argument parsing from command execution. 
However, I still use ptty for the GUI, but do not want to load the whole lib in every case (or depend on jQuery).

So my function is still not perfect, I will take a look at v.0.0.5 tokenizer maybe its better than my...
