### ISSUE TITLE
Use as a console

### ISSUE THREAD

**Issue by GerhardKreuzer** [pachanka/Ptty#6]
Hi,
looking for a web site element, I can use as a console for a remote micro processor.
I just Need to get a string after typing something in. This should be send to the Server with a AJAX/JSON/POST and the Server will Forward this string via Serial line to the CLI running on the micro. The micro hopfully sends an answer back via Serial line and the Server put this info into a JSON Response, which will be used to Show on the Screen.
I don't Need any additional functionality, no command Registration or whatever.
Is it possible to have this element on a partial view?
I use AngularJS and ng-route throughout the rest of my Project.

Thanks a lot for helping.

With best regards

Gerhard

**Comment by pachanka** [comment]
If I understand your requirements correctly, it seems like Ptty isn't what you need. [Here is a command line emulator](https://vtortola.github.io/ng-terminal-emulator/) that uses Angular js, since you already have it in your specs it might be a better approach.

Hope this helps.
