### ISSUE TITLE
Example of a command with multiple options

### ISSUE THREAD

**Issue by InvisaMage** [pachanka/Ptty#7]
Hi. Really awesome plugin. However, I was wondering how I would go about making a command with multiple options.

I know on the third line I've got to specify what they are but how do I set what they do?

**Comment by pachanka** [comment]
Hi, the fourth argument of `$.register_command()` can be a string (to an ajax resource), or a javascript function, if you use the function you can see the arguments passed:

<pre>$.register_command(
    'options', 
    'options help.', 
    'options usage.',
    function(cmd){
        console.log(cmd);
        var tk = $.tokenize(cmd.join(' '), ['-opt','-opt2']);
        return cmd;
    }
);</pre>

If you run the command `options -opt "hello world" -opt2 hello2` you will see the value of `cmd` will be:

> `Array [ "options", "-opt", ""hello", "world"", "-opt2", "hello2" ]`

The value of `tk` will be:

> `Object { -opt: "hello world", -opt2: "hello2" }`

If you are running an AJAX call, you will get a POST using the "cmd" parameter. But you will have to tokenize the data yourself.

**Comment by InvisaMage** [comment]
What do you mean by tokenizing the data?

**Comment by pachanka** [comment]
By "tokenize the data" I mean convert the command string in to tokens you can then use to know which options were used. Ptty makes this easy with the tokenize method shown above. It takes an array of strings as the options to look for in the first parameter.

For example:

<pre>var tokens = $.tokenize('command --desc "Hello world"', ['--desc']);
// Returns { --desc : "Hello world" }</pre>

Here is the answer to your original question in  a function that expects -v and -c as options:

<pre>$.register_command(
    'command', 
    'help.', 
    'usage.',
    function(cmd){
        var tokens = $.tokenize(cmd.join(' '), ['-v','-c']);
        if(tokens.hasOwnProperty('-v') && tokens.hasOwnProperty('-c')){
            cmd.out = '-v and -c set.';
        }else if(tokens.hasOwnProperty('-v')){
            cmd.out = '-v is set.';
        }else if(tokens.hasOwnProperty('-c')){
            cmd.out = '-c is set.';
        }else{
            cmd.out = 'no options used.';
        }
        return cmd;
    }
);</pre>

**Comment by InvisaMage** [comment]
Ohhh, okay. Thanks a bunch.
