### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by JordanDevelop** [pachanka/Ptty#8]
How do I allow typing on mobile? I can't seem to open the keyboard on my iPhone.

**Comment by pachanka** [comment]
Hi. There seems to be no support for `contenteditable` below iOS 5, but it could be something else. Perhaps the focus call is not binding with the input div.

Here is some untested code:
```

    $(document).ready(function(){
        var $ptty = $('#terminal').Ptty();
        // Try and open keyboard
        $('#terminal').on('touchstart', function(){
             $(this).find('.input').focus();
             // Or... $(this).find('.input').click();
        });
    });

```
Let me know if that works.

If it doesn't you can always try and add a text input and clone all its content to the `# terminal .input` div.

`<input type="text" id="iphone-hack" style="width: 0;  height: 0; opacity: 0; position: absolute;">  `

And then something like (again untested):

```
var $input = $ptty.get_terminal().find('.input');
$('#iphone-hack').on('keyup', function(e){
    
    if(e.which == 13) {
        $(this).val('');
        // See: http://goto.pachanka.org/ptty/docs/#run_command
        $ptty.run_command($(this).val(''));
    }else{
        $input.val($(this).val());
    }
});
```

**Comment by pachanka** [comment]
Closed due to lack of debugging input.
